spring:
  application:
    name: engine
eureka:
  client:
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 3
application:
  input-queue: D:/engine-queue
  output-queue: D:/queues
  messages-queue-size: 1000000
  wait-for-calculator-in-sec: 60
  calculator:
    name: dpCalculator
    path: c:/Users/Hatim/IdeaProjects/jvm/build/libs/jvm-1.jar
    args: -DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector -Dlog4j2.asyncLoggerWaitStrategy=Sleep
    number: 5