spring:
  application:
    name: engine
eureka:
  client:
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 3
application:
  output-queue: D:/queues
  messages-queue-size: 1000000
  calculator:
    name: dpCalculator
    path: c:/Users/Hatim/IdeaProjects/jvm/build/libs/jvm-1.jar
    number: 5