spring:
  application:
    name: engine
server:
  port: 8080
eureka:
  client:
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 3
